openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:8081/
paths:
  /:
    get:
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
        '400':
          description: Invalid parameters provided
    post:
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
        - name: value
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
        '400':
          description: Invalid parameters provided
